### ISSUE TITLE
data_loder.py

### ISSUE THREAD

**Issue by Xuran-LI** [philips-george/ifv-uai-2020#1]

**Comment by philips-george** [comment]
The code for ibv.model is in the dev-pkgs/ subdirectory of the repository. This directory should already be added to PYTHONPATH in code using sys.path,insert(...) in the main Python scripts. The InputVariable class stores the type (real, integer) as well as upper and lower bounds for each input feature. Our code does not do any one-hot-encoding unless a particular feature is one-hot-encoded already.

It should be possible to run the bias verification experiments directly if you clone the entire repository into a local directory, change to the experiments subdirectory, and run the scripts there (as described in the README). This is provided the required python packages have been installed (Note: CPLEX is required for the linear and rbf cases, SDPA is required for the polynomial case). Please do let us know of any specific issues.
